name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    outputs:
      release-body: ${{ steps.changelog.outputs.content }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: orhun/git-cliff-action@v2
        id: changelog
        with:
          args: --latest --strip header

  release:
    needs: [generate-changelog]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish

      - name: Create Github release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ needs.generate-changelog.outputs.release-body }}
